### ISSUE TITLE
Unable to build packages/table

### ISSUE THREAD

**Issue by 0x0dr1y** [mtorromeo/vue-patternfly#7]
Hey, long time no see! :)  

I'm currently trying to build the table packages and it seems to fail for multiple reasons.

I'm using `pnpm build` in the package and straight up run into errors:

```
> vite build

vite v5.4.2 building for production...
✓ 0 modules transformed.
x Build failed in 308ms
error during build:
[vite:vue] [@vue/compiler-sfc] Failed to resolve extends base type.
If this previously worked in 3.2, you can instruct the compiler to ignore this extend by adding /* @vue-ignore */ before it, for example:

interface Props extends /* @vue-ignore */ Base {}

Note: both in 3.2 or with the ignore, the properties in the base type are treated as fallthrough attrs at runtime.

/home/nihirsch/workspace-github/vue-patternfly/packages/table/src/Tr.vue
39 |  const ariaLabel = computed(() => {
40 |    if (props.ariaLabel) {
41 |      return props.ariaLabel;
   |        ^^^^^^^^^
42 |    }
43 |    if (!props.selectable || isHidden.value) {
```

Another error which seems to be around when building the esm stuff for example:
```
src/common.ts:1:50 - error TS2307: Cannot find module '@vue-patternfly/core' or its corresponding type declarations.

1 import type { ChildrenTrackerInjectionKey } from '@vue-patternfly/core';
```

Am i missing something obvious or are the build scripts currently broken for the table package? Thanks!

**Comment by 0x0dr1y** [comment]
Indeed it was something very obvious.

After building`/core` all i had to do was to run `pnpm install` to get the latest build output of core :) I think yarn workspaces handles that dynamically iirc while pnpm doesn't.

**Comment by mtorromeo** [comment]
I'm using https://turbo.build/ to coordinate the build process. You can just run `pnpm build` / `turbo run build` in the root directory
